language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag udagram-api-feed ialkamal/udagram-api-feed:v1
  - docker tag udagram-api-user ialkamal/udagram-api-user:v1
  - docker tag udagram-frontend ialkamal/udagram-api-frontend:v1
  - docker tag reverseproxy ialkamal/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ialkamal/udagram-api-feed:v1
  - docker push ialkamal/udagram-api-user:v1
  - docker push ialkamal/udagram-frontend:v1
  - docker push ialkamal/udagram-reverseproxy:v1
